# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f77995678361b6fa34f85c2c1c47c9f8"
application_url = "https://applied-rely-warning-vista.trycloudflare.com"
embedded = true
name = "ia-swatch-combined-listing"
handle = "ia-swatch-combined-listing"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://applied-rely-warning-vista.trycloudflare.com/auth/callback",
  "https://applied-rely-warning-vista.trycloudflare.com/auth/shopify/callback",
  "https://applied-rely-warning-vista.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "otaku231.myshopify.com"
automatically_update_urls_on_dev = true
